  spring:
    application:
      name: dine-in-order-api

#DATASTRUCTRE CONFIGRATION
    datasource:
      url: ${MYSQL_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update


  app:
    base-url: /api/v1



